const Data = [];

// export const productData = [
//   {
//     id: 1,
//     name: "Quisque fringilla",
//     primaryImage: "/images/product/01.jpg",
//     secondaryImage: "/images/product/02.jpg",
//     price: 220,
//     quantity: 1,
//     isNew: true,
//   },
//   {
//     id: 2,
//     name: "Elegant Dress",
//     primaryImage: "/images/product/03.jpg",
//     secondaryImage: "/images/product/04.jpg",
//     quantity: 1,
//     price: 220,
//   },
//   {
//     id: 3,
//     name: "Summer Top",
//     primaryImage: "/images/product/02.jpg",
//     secondaryImage: "/images/product/03.jpg",
//     price: 220,
//     isSale: true,
//     quantity: 1,
//     rating: 4,
//   },
//   {
//     id: 4,
//     name: "Casual Shoes",
//     primaryImage: "/images/product/05.jpg",
//     secondaryImage: "/images/product/06.jpg",
//     price: 220,
//     oldPrice: 250,
//     quantity: 1,
//     rating: 4,
//   },
// ];

export const productData = [
  {
    id: 1,
    name: "Quisque fringilla",
    primaryImage: "/images/product/01.jpg",
    secondaryImage: "/images/product/02.jpg",
    price: 220,
    oldPrice: null,
    quantity: 1,
    isNew: true,
    isSale: false,
    rating: 3,
  },
  {
    id: 2,
    name: "Elegant Dress",
    primaryImage: "/images/product/03.jpg",
    secondaryImage: "/images/product/04.jpg",
    price: 220,
    oldPrice: null,
    quantity: 1,
    isNew: false,
    isSale: false,
    rating: 4,
  },
  {
    id: 3,
    name: "Summer Top",
    primaryImage: "/images/product/02.jpg",
    secondaryImage: "/images/product/03.jpg",
    price: 220,
    oldPrice: null,
    quantity: 1,
    isNew: false,
    isSale: true,
    rating: 4,
  },
  {
    id: 4,
    name: "Casual Shoes",
    primaryImage: "/images/product/05.jpg",
    secondaryImage: "/images/product/06.jpg",
    price: 220,
    oldPrice: 250,
    quantity: 1,
    isNew: false,
    isSale: false,
    rating: 4,
  },
];
