const Data = [];

// old data
// export const productData = [
//   {
//     id: 1,
//     name: "Quisque fringilla",
//     primaryImage: "/images/product/01.jpg",
//     secondaryImage: "/images/product/02.jpg",
//     price: 220,
//     quantity: 1,
//     isNew: true,
//   },
//   {
//     id: 2,
//     name: "Elegant Dress",
//     primaryImage: "/images/product/03.jpg",
//     secondaryImage: "/images/product/04.jpg",
//     quantity: 1,
//     price: 220,
//   },
//   {
//     id: 3,
//     name: "Summer Top",
//     primaryImage: "/images/product/02.jpg",
//     secondaryImage: "/images/product/03.jpg",
//     price: 220,
//     isSale: true,
//     quantity: 1,
//     rating: 4,
//   },
//   {
//     id: 4,
//     name: "Casual Shoes",
//     primaryImage: "/images/product/05.jpg",
//     secondaryImage: "/images/product/06.jpg",
//     price: 220,
//     oldPrice: 250,
//     quantity: 1,
//     rating: 4,
//   },
// ];

//updated

export const productData = [
  {
    id: 1,
    name: "Quisque fringilla",
    primaryImage: "/images/product/01.jpg",
    secondaryImage: "/images/product/02.jpg",
    price: 220,
    oldPrice: null,
    quantity: 1,
    isNew: true,
    isSale: false,
    rating: 3,
    images: [
      "images/product/01.jpg",
      "images/product/02.jpg",
      "images/product/03.jpg",
      "images/product/04.jpg",
    ],
    description:
      "A trendy and comfortable outfit designed for everyday wear. Made from soft, breathable fabric with a perfect fit for any occasion.",
    colors: ["Red", "Blue", "Green", "Purple", "Black", "White"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: 2,
    name: "Elegant Dress",
    primaryImage: "/images/product/03.jpg",
    secondaryImage: "/images/product/04.jpg",
    price: 220,
    oldPrice: null,
    quantity: 1,
    isNew: false,
    isSale: false,
    rating: 4,
    images: [
      "images/product/01.jpg",
      "images/product/02.jpg",
      "images/product/03.jpg",
      "images/product/04.jpg",
    ],
    description:
      "An elegant and classy dress made from premium-quality fabric. Perfect for formal gatherings, parties, and special occasions.",
    colors: ["Black", "Maroon", "Navy Blue", "Emerald Green"],
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: 3,
    name: "Summer Top",
    primaryImage: "/images/product/02.jpg",
    secondaryImage: "/images/product/03.jpg",
    price: 220,
    oldPrice: null,
    quantity: 1,
    isNew: false,
    isSale: true,
    rating: 4,
    images: [
      "images/product/01.jpg",
      "images/product/02.jpg",
      "images/product/03.jpg",
      "images/product/04.jpg",
    ],
    description:
      "Lightweight and breezy summer top made with cotton blend fabric. Ideal for sunny days and casual outings.",
    colors: ["Yellow", "Peach", "Sky Blue", "White"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 4,
    name: "Casual Shoes",
    primaryImage: "/images/product/05.jpg",
    secondaryImage: "/images/product/06.jpg",
    price: 220,
    oldPrice: 250,
    quantity: 1,
    isNew: false,
    isSale: false,
    rating: 4,
    images: [
      "images/product/01.jpg",
      "images/product/02.jpg",
      "images/product/03.jpg",
      "images/product/04.jpg",
    ],
    description:
      "Durable and stylish casual shoes offering all-day comfort. Designed with premium materials and a cushioned sole for maximum support.",
    colors: ["Black", "White", "Grey", "Brown"],
    sizes: ["6", "7", "8", "9", "10", "11"],
  },
];
